services:
  backend-node:
    build: ./backend-node
    container_name: backend-node
    env_file:
      - .env
    ports:
      - "4000:4000"

  backend-python:
    build: ./backend-python
    container_name: backend-python
    env_file:
      - .env
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend-react
    container_name: frontend
    ports:
      - "3000:80"

volumes:
  pgdata-dev:
  pgdata-stage:
